export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const TOGGLE_MOBILE_DRAWER = 'TOGGLE_MOBILE_DRAWER';
export const SET_MOBILE_DRAWER = 'SET_MOBILE_DRAWER';

export const SET_IS_LARGE = 'SET_IS_LARGE';
export const TOGGLE_IS_LARGE = 'TOGGLE_IS_LARGE';